fix(build): Fix broken build with StringView change
Summary:
I think this is a left-over from Pedro's StringView change, which currently broke the build. I hope this is the only place broken, I couldn't verify this locally.
```
/__w/velox/velox/velox/connectors/hive/storage_adapters/s3fs/tests/S3MultipleEndpointsTest.cpp:105:42: error: no matching function for call to 'parseJson(const facebook::velox::StringView)'
  105 |     folly::dynamic obj = folly::parseJson(details->valueAt(1));
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

Differential Revision: D90528368