refactor(cudf): Fix velox_cudf_hive_connector dependencies (#15087)
Summary:
Remove velox_cudf_hive_config library as it is not required.
cudf::cudf has to be a public dependency on velox_cudf_hive_connector due to the build error below.
Remove other unrelated dependencies.
Add a log message for the constructor.
```
/deepak/presto/presto-native-execution/velox/velox/experimental/cudf/connectors/hive/CudfHiveConfig.h:21:10: fatal error: cudf/types.hpp: No such file or directory
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/15087

Reviewed By: xiaoxmeng

Differential Revision: D84640709

Pulled By: kKPulla

fbshipit-source-id: 03d7b4ab46f0ce74448db79e2c6b9a7643462f05