fix(HashJoin): Stop HashProbe filter evaluation when filter input has no selections (#11911)
Summary:

This change stops filter evaluation when `filterInputRows_` has no selections. Evaluating the filter when `filterInputRows_` has no selections can result in `filterResult_` being in an invalid state and cause index out of range errors when attempting to access it.

```
Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (128 vs. 128) Dictionary index must be less than base vector's size. Index: 128.
Retriable: False
Expression: rawIndices_[i] < dictionaryValues_->size()
Context: Top-level Expression: gt(cast((t_k1) as BIGINT), 1000:BIGINT)
Additional Context: Operator: HashProbe[2] 1
Function: validate
File: buck-out/v2/gen/fbcode/16b07710e10499f0/velox/vector/__velox_vector__/buck-headers/velox/vector/DictionaryVector-inl.h
Line: 215
```

Reviewed By: kevinwilfong

Differential Revision: D67420798