fix: Update numeric limits to parallel type due to compilation errors (#13657)
Summary:

Update Velox check to compare against same types. Since weighted count is a double, we need to adjust the numeric limit to also a double. This was causing issues in Presto that uses a different (more strict) compiler:

```
/__w/presto/presto/presto-native-execution/velox/velox/functions/lib/QuantileDigest.h:555:7: error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]
      std::numeric_limits<int64_t>::max(),
```

Differential Revision: D76060944