Make 'function not registered' a user error
Summary:
Missing features should be reported as user errors, not system errors.

```
VeloxRuntimeError:  Scalar function name not registered: presto.default.at_timezone
```

After this change, the message about would use VeloxUserError.

Differential Revision: D46391342

fbshipit-source-id: 0ec5574464d663df86df12be1cd33467af098c1c