Revert "Remove static driver executor (#820)"
This reverts commit 55812a98aa175b810f0928c61d2b6b35497a48b9.
55812a98 is causing build break on presto_cpp:

/Users/yingsu/repo/presto_cpp3/presto_cpp/presto_cpp/main/PrestoServer.cpp:228:28: error: no member named 'executor' in 'facebook::velox::exec::Driver'
      velox::exec::Driver::executor(),
      ~~~~~~~~~~~~~~~~~~~~~^
/Users/yingsu/repo/presto_cpp3/presto_cpp/presto_cpp/main/PrestoServer.cpp:258:43: error: no member named 'executor' in 'facebook::velox::exec::Driver'
  auto cpuExecutor = velox::exec::Driver::executor();
                     ~~~~~~~~~~~~~~~~~~~~~^