build: remove decl+set of unused variable (#12435)
Summary:

This avoids the following errors:

  velox/core/PlanNode.cpp:935:15: error: variable 'dereference' set but not used [-Werror,-Wunused-but-set-variable]

Reviewed By: dtolnay

Differential Revision: D70055975