feat(cudf): Bypass cudf folder in clang-tidy check (#17170)
Summary:
Extract from https://github.com/facebookincubator/velox/pull/16760 to solve
```
# Dependency .clang-tidy config errors:
_build/release/_deps/rmm-src/cpp/.clang-tidy:16:1: error: unknown key 'AnalyzeTemporaryDtors'
_build/release/_deps/cudf-src/cpp/.clang-tidy:53:1: error: unknown key 'ExcludeHeaderFilterRegex'

# CUDA compiler flag errors (clang-tidy doesn't understand nvcc flags):
error: GPU arch sm_35 is supported by CUDA versions between 7.0 and 11.8 (inclusive)
error: unknown argument: '--extended-lambda'
error: unknown argument: '--generate-code=arch=compute_70,code=[compute_70,sm_70]'
error: unknown argument: '-Xcompiler=-fPIC'
error: unknown argument: '-ccbin'
error: unknown argument: '-forward-unknown-to-host-compiler'

# Missing CUDA header:
__clang_cuda_runtime_wrapper.h:486:10: error: 'curand_mtgp32_kernel.h' file not found

# Files that failed clang-tidy processing:
[6/10]  velox/experimental/cudf/exec/util/InteropUtil.h
[7/10]  velox/experimental/cudf/tests/CudfFunctionBaseTest.h
[8/10]  velox/experimental/cudf/tests/InteropTest.cpp
[9/10]  velox/experimental/cudf/tests/SubfieldFilterAstTest.cpp
[10/10] velox/experimental/cudf/tests/utils/CudfHiveConnectorTestBase.cpp
```
Also resolve the issue in https://github.com/facebookincubator/velox/pull/16750

Pull Request resolved: https://github.com/facebookincubator/velox/pull/17170

Reviewed By: kgpai

Differential Revision: D101388357

Pulled By: peterenescu

fbshipit-source-id: cf386c0706d31672cf1cf7ddcac607a009a4281f