fix: Moving a local variable in return statements in BingTileFunctions.h is causing builds to fail (#14190)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/14190

Builds are currently failing with the following error message

 error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]

referring to the lines recently added to BingTileFunctions.h which do

return std::move(zoomCheck);

The fix is to remove the std::move and let the compiler do it automatically.

D78198453 introduced the code in question.

Reviewed By: Sullivan-Patrick, kgpai

Differential Revision: D78769633