refactor: Use `re2::StringPiece` for `RE2::FullMatch()` (#15259)
Summary:
`RE2::FullMatch()` uses `absl::string_view` not `std::string_view`:

https://github.com/google/re2/blob/61c4644171ee6b480540bf9e569cba06d9090b4b/re2/re2.h#L411

`absl::string_view` may not be an alias of `std::string_view`. In the case, the following error is reported:

```text
In file included from velox/functions/prestosql/registration/DateTimeFunctionsRegistration.cpp:18:
velox/functions/prestosql/DateTimeFunctions.h:1939:10: error: no matching function for call to 'FullMatch'
 1939 |     if (!RE2::FullMatch(
      |          ^~~~~~~~~~~~~~
/include/re2/re2.h:411:15: note: candidate function template not viable: no known conversion from 'std::string_view' (aka 'basic_string_view<char>') to 'absl::string_view' for 1st argument
  411 |   static bool FullMatch(absl::string_view text, const RE2& re, A&&... a) {
      |               ^         ~~~~~~~~~~~~~~~~~~~~~~
```

Old RE2 that is provided by CentOS Stream 9 doesn't accept `absl::string_view`.

Old RE2 uses `re2::StringPiece` for `RE2::FullMatch()` and new RE2 provides `re2::StringPiece` as an alias of `absl::string_view`. So we can use `re2::StringPiece` for both of old and new RE2.

We can drop support for old RE2 to always use `absl::string_view` but we use `re2::StringPiece` for now. It seems that RE2 will use `std::string_view` instead of `absl::string_view` eventually. For example, https://github.com/google/re2/commit/2a029e28d3080e4718581649ba9faad5347c3ff9 is a commit to migrate to `std::optional` from `absl::optional`.

We can revisit this after RE2 migrates to `std::string_view`.

Related: GH-15124

Pull Request resolved: https://github.com/facebookincubator/velox/pull/15259

Reviewed By: kevinwilfong

Differential Revision: D85539525

Pulled By: mbasmanova

fbshipit-source-id: 1dde1c47d7a337d220488aa64b5efa3408876d1e