fix eden fs build with GCC 13.2.1 (#7070)
Summary:

fix eden fs build with GCC 13.2.1

Fixing two problems that broke builds on Fedora 38, which comes with GCC 13.2.1

   * GCC 13.2.1 can't build the old rocksdb, so update the version
   * there was a missing include in BackingStoreType.h

X-link: https://github.com/facebook/sapling/pull/748

Test Plan:
build locally with:
```
./build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. --project-install-prefix eden:/usr/local eden
```

Before, eden fs build breaks at rocksdb on uint8_t
```
FAILED: CMakeFiles/rocksdb.dir/table/block_based/data_block_hash_index.cc.o
/usr/bin/c++ -DLZ4 -DOS_LINUX -DROCKSDB_FALLOCATE_PRESENT -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_NO_DYNAMIC_EXTENSION -DROCKSDB_PLATFORM_POSIX -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -DSNAPPY -I/home/alex/local/tmp/fridge/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/extracted/rocksdb-v7.7.3.tar.gz/rocksdb-7.7.3 -I/home/alex/local/tmp/fridge/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/extracted/rocksdb-v7.7.3.tar.gz/rocksdb-7.7.3/include -isystem /home/alex/local/tmp/fridge/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/extracted/rocksdb-v7.7.3.tar.gz/rocksdb-7.7.3/third-party/gtest-1.8.1/fused-src -W -Wextra -Wall -pthread -Wsign-compare -Wshadow -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-invalid-offsetof -fno-omit-frame-pointer -momit-leaf-frame-pointer -fno-builtin-memcmp -O2 -g -DNDEBUG -std=gnu++17 -MD -MT CMakeFiles/rocksdb.dir/table/block_based/data_block_hash_index.cc.o -MF CMakeFiles/rocksdb.dir/table/block_based/data_block_hash_index.cc.o.d -o CMakeFiles/rocksdb.dir/table/block_based/data_block_hash_index.cc.o -c /home/alex/local/tmp/fridge/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/extracted/rocksdb-v7.7.3.tar.gz/rocksdb-7.7.3/table/block_based/data_block_hash_index.cc
In file included from /home/alex/local/tmp/fridge/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/extracted/rocksdb-v7.7.3.tar.gz/rocksdb-7.7.3/table/block_based/data_block_hash_index.cc:9:
/home/alex/local/tmp/fridge/fbcode_builder_getdeps-ZhomeZalexZlocalZsaplingZbuildZfbcode_builder/extracted/rocksdb-v7.7.3.tar.gz/rocksdb-7.7.3/table/block_based/data_block_hash_index.h:65:7: error: ‘uint8_t’ does not name a type
   65 | const uint8_t kNoEntry = 255;
      |       ^~~~~~~
/home/alex/local/tmp/fridge/fbc
```

After, works

Reviewed By: mitrandir77

Differential Revision: D50313436

Pulled By: genevievehelsel