Fix build failure caused by undefined reference to registerAllAggregateFunctions() (#2842)
Summary: Pull Request resolved: https://github.com/facebookincubator/velox/pull/2842

Reviewed By: mbasmanova

Differential Revision: D40371142

fbshipit-source-id: ffe51afdfd5f677fea90fdb46444764bac3c5f60