fix(build): Dwrf proto build error (#17716)
Summary:
```
/velox/velox/dwio/dwrf/utils/test/TypeAttributesTest.cpp:90:22: error: no member named 'attributes' in 'facebook::velox::dwrf::proto::Type'
   90 |     EXPECT_EQ(parsed.attributes(i).value(), kIcebergAttrs[i].second);
```

Root cause is stale protobuf generation, dwrf_proto.proto changed, but the protoc rule did not depend on the .proto inputs, so builds could keep using an old dwrf_proto.pb.h without the new changes.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/17716

Reviewed By: HuamengJiang

Differential Revision: D107967107

Pulled By: xiaoxmeng

fbshipit-source-id: b427e94ea7aac8201fce4c8b5928208fe2c433a5