Rename State enum members in TestColumnStatistics
The State enum members' name collide with boolean.h in MacOsX SDK. The
error messages from running "make" on newly cloned repo are like the
following:

/Users/yingsu/repo/velox2/velox/velox/dwio/dwrf/test/TestColumnStatistics.cpp:605:16: error: expected identifier
  enum State { TRUE = 0, FALSE, MISSING };
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/mach/boolean.h:81:17: note: expanded from macro 'TRUE'
                ^
/Users/yingsu/repo/velox2/velox/velox/dwio/dwrf/test/TestColumnStatistics.cpp:605:26: error: expected identifier
  enum State { TRUE = 0, FALSE, MISSING };
                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/mach/boolean.h:85:17: note: expanded from macro 'FALSE'
                ^