refactor: Remove usage of arrow/util/logging.h (#14005)
Summary:
`arrow/util/logging.h` conflicts with `glog/logging.h`

```
In file included from /Users/runner/work/presto/presto/presto-native-execution/velox/velox/dwio/parquet/writer/arrow/Writer.cpp:40:
In file included from /Users/runner/work/presto/presto/presto-native-execution/velox/velox/common/base/Exceptions.h:27:
In file included from /Users/runner/work/presto/presto/presto-native-execution/velox/velox/common/base/VeloxException.h:27:
/usr/local/include/glog/logging.h:1320:9: error: 'DCHECK_GE' macro redefined [-Werror,-Wmacro-redefined]
#define DCHECK_GE(val1, val2) CHECK_GE(val1, val2)
        ^
/Users/runner/work/presto/presto/presto-native-execution/_build/Debug/velox/CMake/resolve_dependency_modules/arrow/arrow_ep/install/include/arrow/util/logging.h:146:9: note: previous definition is here
#define DCHECK_GE ARROW_DCHECK_GE
```

Pull Request resolved: https://github.com/facebookincubator/velox/pull/14005

Reviewed By: peterenescu

Differential Revision: D85248955

Pulled By: mbasmanova

fbshipit-source-id: 19e916d52caf26888308b9b34b9bf5d6a8c7f461