fix: Spurious compiler error due to deep inlining (#16002)
Summary:

Ubuntu release build gives the following error due to GCC's spurious deep inlining optimization when inlining creation of StringViews : 
```
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ writing 13 or more bytes into a region of size 12 overflows the destination [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This fixes it by letting the compiler know that its not possible to have length > 12 in the inlining case. 
Fixes https://github.com/facebookincubator/velox/issues/15245

Differential Revision: D90620860