Fix protobuf error during build when using Velox as a module of other CMake project
Error message:

```
/opt/velox4j/src/main/cpp/cmake-build-debug/_deps/velox-src/velox/dwio/dwrf/common/wrap/dwrf-proto-wrapper.cpp:37:10: fatal error: velox/dwio/dwrf/proto/dwrf_proto.pb.cc: No such file or directory
   37 | #include "velox/dwio/dwrf/proto/dwrf_proto.pb.cc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated
```

This is because the generated `protoc` command relies on the root CMake project path so will be messed up when Velox is used as a module as other CMake projects.

The patch fixes the issue.