Bring back OBJECT to add_library(velox_hive_connector).
Summary:
Removing OBJECT breaks build of executables with errors like below.
  undefined reference to HiveTableHandle::HiveTableHandle()
We suspect it is because some unused symbols get removed from
the *.a library and later cannot be found when linking an executable.

The PR that broke this:
https://github.com/facebookincubator/velox/pull/2809
Example of the linking error:
https://github.com/prestodb/presto/actions/runs/3285240930/jobs/5412120705

Reviewed By: mbasmanova

Differential Revision: D40538062

fbshipit-source-id: 793d8e2fba186f4c079d2d7c2c1949969a834f81