build: fix llvm-19-exposed -Wmissing-template-arg-list-after-template-kw warning (#12458)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/12458

This avoids the following errors:

  velox/functions/prestosql/Comparisons.cpp:93:24: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]

Removing the template keyword is fine, because the compiler can deduce the type of the lambda.

Reviewed By: kgpai, dtolnay

Differential Revision: D70226049