fix(build): Ambiguity caused by long literal (#15670)
Summary:
Fixes the below compilation exception caused by long ambiguity.

```
velox/exec/tests/utils/ExpressionBuilder.h:463:10: error: call to 'lit' is ambiguous
  463 |   return lit(value);
      |          ^~~
```

Error log: https://github.com/facebookincubator/velox/actions/runs/19849127249/job/56872221626?pr=15536

Pull Request resolved: https://github.com/facebookincubator/velox/pull/15670

Reviewed By: kagamiori

Differential Revision: D88180024

Pulled By: kgpai

fbshipit-source-id: 5b167f6105ced9d7ca0e3fc34041c2fc5a1b139f