remove unused variable from the function decodeArrayElements
Summary:
Seeing the following error during build diff due to unused variable

```
Stdout: <empty>
Stderr:
fbcode/velox/functions/prestosql/ArrayIntersectExcept.cpp:143:8: error: unused variable 'decodedVector' [-Werror,-Wunused-variable]
  143 |   auto decodedVector = arrayDecoder.get();
      |        ^~~~~~~~~~~~~
1 error generated.
```

Differential Revision: D67071311