Allow invalid UTF-8 in cast(varchar as json)
Summary:
In Presto, cast(varchar as json) allows invalid UTF-8 characters and replaced
them with U+FFFD. We need to do the same.

Without this change, queries fails with

```
VeloxUserError:  folly::utf8ToCodePoint i=2 tmp=22 cast((array_agg) as JSON)
```

Differential Revision: D56546383